name = "ERA5_Analysis"
uuid = "a4f775dc-9ac1-4079-aa93-d12d58c0fe66"
authors = ["Jesse <jesbrirob@gmail.com>"]
version = "0.1.0"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
