const PROJECTPATH = joinpath(@__DIR__, ".." , "..")
const NRCSDATA = joinpath(PROJECTPATH, "NRCS Cleansing", "data")
const NOHRSCDATA = joinpath(PROJECTPATH, "NOHRSC Cleansing", "data")
const ERA5DATA = joinpath(PROJECTPATH, "ERA5 Data")
const COMPARISONS = joinpath(PROJECTPATH, "COMPARISONS")